[default]
src = 'src'
out = 'out'
libs = ['lib']
solc_version = "0.8.10"
remappings = [
    'ds-test/=lib/ds-test/src/',
    '@openzeppelin=node_modules/@openzeppelin/',
    '@rari-capital/solmate/=node_modules/@rari-capital/solmate/',
    'aave-v3-core/=lib/aave-v3-core/',
    'forge-std/=lib/forge-std/src/',
    'aave-stake-v2/=lib/aave-stake-v2/',
]

# See more config options https://github.com/gakonst/foundry/tree/master/config